import { PrismaClient, QuestionsType } from "@prisma/client";

async function main(prisma: PrismaClient) {
    const questions = [
        {
            step: 1,
            question: 'What is your gender?',
            answers: [
                { answer: "Male", name: "male" },
                { answer: "Female", name: "female" },
                { answer: "Non-binary", name: "nonBinary" }
            ],
            name: "gender",
            type: QuestionsType.single,
        },
        {
            step: 2,
            question: 'What is your sexual orientation?',
            answers: [
                { answer: "Straight", name: "straight" },
                { answer: "Gay", name: "gay" },
                { answer: "Bisexual", name: "bisexual" },
                { answer: "Other", name: "other" }
            ],
            name: "sexualOrientation",
            type: QuestionsType.single,
        },
        {
            step: 3,
            question: 'Ethnicity',
            answers: [
                { answer: "White", name: "white" },
                { answer: "Black", name: "black" },
                { answer: "Asian", name: "asian" },
                { answer: "Mixed", name: "mixed" },
                { answer: "Other", name: "other" }
            ],
            name: "ethnicity",
            type: QuestionsType.single
        },
        {
            step: 4,
            question: 'How old are you?',
            answers: [
                { answer: "18-20", name: "18-20" },
                { answer: "21-25", name: "21-25" },
                { answer: "26-30", name: "26-30" },
                { answer: "31-35", name: "31-35" },
                { answer: "36-40", name: "36-40" },
                { answer: "41-45", name: "41-45" },
                { answer: "46-50", name: "46-50" },
                { answer: "51-60", name: "51-60" },
                { answer: "60+", name: "60+" }
            ],
            name: "age",
            type: QuestionsType.single,
        },
        {
            step: 5,
            question: 'What is your current relationship status?',
            answers: [
                { answer: "Single", name: "single" },
                { answer: "Commited relationship/Married", name: "commitedRelationship" },
                { answer: "It's complicated", name: "itsComplicated" },
                { answer: "Separated / Divorced / Widower", name: "divorced" },
            ],
            name: "relationshipStatus",
            type: QuestionsType.single,
        },
        {
            step: 6,
            question: 'Do you have children',
            answers: [
                { answer: "Yes", name: "yes" },
                { answer: "No", name: "no" },
            ],
            name: "children",
            type: QuestionsType.single
        },
        {
            step: 7,
            question: 'How socially active are you?',
            answers: [
                { answer: "Not active", name: "notActive" },
                { answer: "Somewhat active", name: "somewhatActive" },
                { answer: "Active", name: "active" },
                { answer: "Very active", name: "veryActive" },
                { answer: "Hooked", name: "hooked" }
            ],
            name: "socialActivity",
            type: QuestionsType.slider,
        },
        {
            step: 8,
            question: 'How confident are you in social situations?',
            answers: [
                { answer: "Not at all", name: "notAtAll" },
                { answer: "Just trying", name: "justTrying" },
                { answer: "I am okay with it", name: "okayWithIt" },
                { answer: "Confident", name: "confident" },
                { answer: "Very confident", name: "veryConfident" }
            ],
            name: "confidence",
            type: QuestionsType.slider,
        },
        {
            step: 9,
            question: 'Where do you usually socialize?',
            answers: [
                { answer: "At a restaurant", name: "restaurant" },
                { answer: "At a club", name: "club" },
                { answer: "At the gym", name: "gym" },
                { answer: "At a bar", name: "bar" },
                { answer: "Sports / activities", name: "activities" },
                { answer: "Cafés", name: "cafes" },
                { answer: "At home with friends", name: "home" },
                { answer: "Nowhere", name: "nowhere" },
                { answer: "Social media", name: "socialMedia" },
                { answer: "Work", name: "work" },
                { answer: "College", name: "college" },
            ],
            name: "socialize",
            type: QuestionsType.multiple,
        },
        {
            step: 10,
            question: 'What type of relationships are you looking for?',
            answers: [
                { answer: "Casual no expectation", name: "casual" },
                { answer: "Serious relationship", name: "serious" },
                { answer: "Casual sex", name: "sexual" },
                { answer: "Friendship", name: "friendship" },
                { answer: "Committed relationship", name: "committed" },
                { answer: "Situationship", name: "situationship" },
                { answer: "In a relationship but want to meet other people", name: "inARelationship" }
            ],
            name: "relationshipType",
            type: QuestionsType.multiple,
        },
        {
            step: 11,
            question: 'Which personality traits describe you best?',
            answers: [
                { answer: "Independent", name: "independent" },
                { answer: "Ambitious", name: "ambitious" },
                { answer: "Charitable", name: "charitable" },
                { answer: "Dynamic", name: "dynamic" },
                { answer: "Humorous", name: "humorous" },
                { answer: "Loyal", name: "loyal" },
                { answer: "Passionate", name: "passionate" },
                { answer: "Practical", name: "practical" },
                { answer: "Romantic", name: "romantic" },
                { answer: "Sensitive", name: "sensitive" },
                { answer: "Sociable", name: "sociable" },
                { answer: "Trustworthy", name: "trustworthy" },
                { answer: "Well-read", name: "wellRead" }
            ],
            name: "personalityTraits",
            type: QuestionsType.multiple,
        },
        {
            step: 12,
            question: 'What are your biggest challenges in dating or social life?',
            answers: [
                { answer: "Confidence issues", name: "confidenceIssues" },
                { answer: "Communication problems", name: "communicationProblems" },
                { answer: "I feel I am too old to date", name: "tooOldToDate" },
                { answer: "Running out of time to start family", name: "runningOutOfTime" },
                { answer: "Not happy with appearance", name: "notHappyWithAppearance" },
                { answer: "Weight issues", name: "weightIssues" },
                { answer: "Not happy with my social life", name: "notHappyWithSocialLife" },
                { answer: "Too busy to date", name: "tooBusyToDate" },
                { answer: "Don’t know where to find dates / friends", name: "dontKnowWhereToFindDates" },
                { answer: "No single friends to go out with", name: "noSingleFriends" },
                { answer: "I want to get out of current relationship", name: "wantToGetOutOfCurrentRelationship" },
                { answer: "Burned in relationships", name: "burnedInRelationships" },
                { answer: "Stuck on my ex", name: "stuckOnMyEx" },
                { answer: "I want to increase my dating chances", name: "increaseDatingChances" },
                { answer: "My online dates don’t get a follow up", name: "noFollowUpOnlineDates" },
                { answer: "I often end up in the friend zone", name: "endUpInFriendZone" },
                { answer: "People I like don’t want to date me", name: "peopleDontWantToDateMe" },
                { answer: "Still living with parents", name: "stillLivingWithParents" },
                { answer: "Financial instability", name: "financialInstability" },
                { answer: "Pressure from family / society to start a family", name: "pressureToStartFamily" },
                { answer: "I am away from what I call home", name: "awayFromHome" },
            ],
            name: "biggestChallenges",
            type: QuestionsType.multiple,
        },
        {
            step: 13,
            question: 'Which personality traits describe you best?',
            answers: [
                { answer: "Independent", name: "independent" },
                { answer: "Sociable", name: "sociable" },
                { answer: "Loyal", name: "loyal" },
                { answer: "Charitable", name: "charitable" },
                { answer: "Trustworthy", name: "trustworthy" },
                { answer: "Environmentally aware", name: "environmentallyAware" },
                { answer: "Ambitious", name: "ambitious" },
                { answer: "Reserved", name: "reserved" },
                { answer: "Adventurous", name: "adventurous" },
                { answer: "Shy", name: "shy" },
                { answer: "Passionate", name: "passionate" },
                { answer: "Possessive", name: "possessive" },
                { answer: "Practical", name: "practical" },
                { answer: "Romantic", name: "romantic" },
                { answer: "Dynamic", name: "dynamic" },
                { answer: "Sexual / Erotic", name: "sexualErotic" },
                { answer: "Prudent", name: "prudent" },
                { answer: "Sensitive", name: "sensitive" },
                { answer: "Humorous", name: "humorous" },
                { answer: "Spiritual", name: "spiritual" },
                { answer: "Religious", name: "religious" },
                { answer: "Well Read / Intellectual", name: "wellReadIntellectual" },
                { answer: "Successful", name: "successful" },
                { answer: "Likes tidiness", name: "likesTidiness" },
                { answer: "Pet lover", name: "petLover" },
                { answer: "Vegetarian / Vegan", name: "vegetarianVegan" },
                { answer: "Smoker", name: "smoker" },
                { answer: "Non drinker", name: "nonDrinker" },
                { answer: "Casual drinker", name: "casualDrinker" },
                { answer: "Regular drinker", name: "regularDrinker" },
                { answer: "Bald", name: "bald" },
                { answer: "Facial hair", name: "facialHair" },
                { answer: "Want children", name: "wantChildren" },
                { answer: "Body piercings", name: "bodyPiercings" },
                { answer: "Have tattoos", name: "haveTattoos" }
            ],
            name: "personalityTraits",
            type: QuestionsType.multiple,
        },
        {
            step: 14,
            question: 'We are here to help you achieve your goals. Select all that apply.',
            answers: [
                { answer: "Find relationship I match with", name: "findRelationship" },
                { answer: "Learn how to attract the people I like", name: "learnAttractPeople" },
                { answer: "Improve social life", name: "improveSocialLife" },
                { answer: "Find new friends", name: "findNewFriends" },
                { answer: "Start a family", name: "startFamily" },
                { answer: "Self development", name: "selfDevelopment" },
                { answer: "Improve self confidence", name: "improveSelfConfidence" },
                { answer: "Improve a certain part of my physical appearance", name: "improvePhysicalAppearance" },
                { answer: "Improve body weight", name: "improveBodyWeight" },
                { answer: "Improve sexual life", name: "improveSexualLife" },
                { answer: "Further career", name: "furtherCareer" },
                { answer: "Further education", name: "furtherEducation" },
                { answer: "Fix my finances", name: "fixFinances" },
                { answer: "Move out of parents' house", name: "moveOutParentsHouse" },
                { answer: "I want to move out of my relationship", name: "moveOutRelationship" },
                { answer: "Get over my ex", name: "getOverEx" },
                { answer: "Get out of the friend zone", name: "getOutFriendZone" },
            ],
            name: "goals",
            type: QuestionsType.single,
        },
        {
            step: 15,
            question: 'Do you have a time frame to reach your goals?',
            answers: [
                { answer: "Yes, within a month", name: "month" },
                { answer: "Yes, within six months", name: "sixMonth" },
                { answer: "Yes, within the year", name: "withinYear" },
                { answer: "Yes, but no firm timeframe", name: "noFirmTimeframe" },
                { answer: "No", name: "no" }
            ],
            name: "timeFrame",
            type: QuestionsType.single,
        },
        {
            step: 16,
            question: 'How important is appearance to you?',
            answers: [
                { answer: "Not important", name: "notImportant" },
                { answer: "Somewhat important", name: "somewhatImportant" },
                { answer: "Important", name: "important" },
                { answer: "Very important", name: "veryImportant" },
            ],
            name: "appearance",
            type: QuestionsType.single,
        },
        {
            step: 17,
            question: 'What age group do you prefer in a partner?',
            answers: [
                { answer: "18-20", name: "18-20" },
                { answer: "21-25", name: "21-25" },
                { answer: "26-30", name: "26-30" },
                { answer: "31-35", name: "31-35" },
                { answer: "36-40", name: "36-40" },
                { answer: "41-45", name: "41-45" },
                { answer: "46-50", name: "46-50" },
                { answer: "51-60", name: "51-60" },
                { answer: "60+", name: "60+" }
            ],
            name: "interestedAge",
            type: QuestionsType.single,
        },
        {
            step: 18,
            question: "Is ethnicity important to you? Select all that apply.",
            answers: [
                { answer: "I don't mind", name: "dontMind" },
                { answer: "White", name: "white" },
                { answer: "Black", name: "black" },
                { answer: "Asian", name: "asian" },
                { answer: "Mixed", name: "mixed" },
                { answer: "Other", name: "other" }
            ],
            name: "interestedEthnicity",
            type: QuestionsType.single
        },
        {
            step: 19,
            question: 'Is body type important to you? Select all that apply.',
            answers: [
                { answer: "I don't mind", name: "dontMind" },
                { answer: "Heavy set", name: "heavySet" },
                { answer: "Athletic", name: "athletic" },
                { answer: "Slim", name: "slim" },
                { answer: "Skinny", name: "skinny" },
                { answer: "A few extra kilos", name: "fewExtraKilos" },
                { answer: "Overweight", name: "overweight" },
            ],
            name: "bodyType",
            type: QuestionsType.multiple,
        },
        {
            step: 20,
            question: 'What type of mate are you looking for? Select all that apply.',
            answers: [
                { answer: "Independent", name: "independent" },
                { answer: "Sociable", name: "sociable" },
                { answer: "Ambitious", name: "ambitious" },
                { answer: "Reserved", name: "reserved" },
                { answer: "Adventurous", name: "adventurous" },
                { answer: "Shy", name: "shy" },
                { answer: "Passionate", name: "passionate" },
                { answer: "Practical", name: "practical" },
                { answer: "Thoughtful", name: "thoughtful" },
                { answer: "Organized", name: "organized" },
                { answer: "Helpful", name: "helpful" },
                { answer: "Charitable", name: "charitable" },
                { answer: "Trustworthy", name: "trustworthy" },
                { answer: "Environmentally aware", name: "environmentallyAware" },
                { answer: "Romantic", name: "romantic" },
                { answer: "Sexual chemistry", name: "sexualChemistry" },
                { answer: "Common interests", name: "commonInterests" },
                { answer: "Loyal", name: "loyal" },
                { answer: "Dynamic", name: "dynamic" },
                { answer: "Prudent", name: "prudent" },
                { answer: "Sensitive", name: "sensitive" },
                { answer: "Humorous", name: "humorous" },
                { answer: "Spiritual", name: "spiritual" },
                { answer: "Religious (active)", name: "religiousActive" },
                { answer: "Well read/Intellectual", name: "wellReadIntellectual" },
                { answer: "College/University graduate", name: "collegeGraduate" },
                { answer: "Smart", name: "smart" },
                { answer: "Financially successful", name: "financiallySuccessful" },
                { answer: "Interested to start a family", name: "startFamily" },
                { answer: "Not married before", name: "notMarriedBefore" },
                { answer: "No children from previous relationships", name: "noChildrenFromPreviousRelationships" },
                { answer: "Cleanliness/tidiness to be high on their list", name: "cleanlinessHigh" },
                { answer: "Pet lover", name: "petLover" },
                { answer: "No animals", name: "noAnimals" },
                { answer: "Vegetarian / Vegan", name: "vegetarianVegan" },
                { answer: "Non smoker", name: "nonSmoker" },
                { answer: "Non drinker", name: "nonDrinker" },
                { answer: "Casual drinker", name: "casualDrinker" },
                { answer: "Regular drinker", name: "regularDrinker" },
                { answer: "Body piercings", name: "bodyPiercings" },
                { answer: "Tall", name: "tall" },
                { answer: "Short", name: "short" },
                { answer: "Sexy", name: "sexy" },
                { answer: "Has tattoos", name: "hasTattoos" },
                { answer: "Local person", name: "localPerson" },
                { answer: "Foreigner", name: "foreigner" },
                { answer: "Of close vicinity", name: "closeVicinity" },
                { answer: "Want children", name: "wantChildren" },
            ],
            name: "mateType",
            type: QuestionsType.multiple,
        },
        {
            step: 21,
            question: 'What is the preferred star sign of your mate?',
            answers: [
                { answer: "I don't mind", name: "dontMind" },
                { answer: "Aries", name: "aries" },
                { answer: "Taurus", name: "taurus" },
                { answer: "Gemini", name: "gemini" },
                { answer: "Cancer", name: "cancer" },
                { answer: "Leo", name: "leo" },
                { answer: "Virgo", name: "virgo" },
                { answer: "Libra", name: "libra" },
                { answer: "Scorpio", name: "scorpio" },
                { answer: "Sagittarius", name: "sagittarius" },
                { answer: "Capricorn", name: "capricorn" },
                { answer: "Aquarius", name: "aquarius" },
                { answer: "Pisces", name: "pisces" },
            ],
            name: "starSign",
            type: QuestionsType.single,
        },
    ];

    for (const question of questions) {
        await prisma.question.upsert({
            where: { question: question.question },
            create: {
                step: question.step,
                question: question.question,
                name: question.name,
                type: question.type,
                answers: {
                    create: question.answers.map(answer => ({
                        answer: answer.answer,
                        name: answer.name,
                    }))
                }
            },
            update: {
                step: question.step,
                question: question.question,
                name: question.name,
                type: question.type,
            }
        });
    }
}

export { main as questionnaireSeed };
