import { ApiProperty } from '@nestjs/swagger';

export enum OrderEventType {
  ORDER_COMPLETED = 'ORDER_COMPLETED',
  ORDER_AUTHORISED = 'ORDER_AUTHORISED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_PAYMENT_AUTHENTICATED = 'ORDER_PAYMENT_AUTHENTICATED',
  ORDER_PAYMENT_DECLINED = 'ORDER_PAYMENT_DECLINED',
  ORDER_PAYMENT_FAILED = 'ORDER_PAYMENT_FAILED',
  PAYOUT_INITIATED = 'PAYOUT_INITIATED',
  PAYOUT_COMPLETED = 'PAYOUT_COMPLETED',
  PAYOUT_FAILED = 'PAYOUT_FAILED',
  DISPUTE_ACTION_REQUIRED = 'DISPUTE_ACTION_REQUIRED',
  DISPUTE_UNDER_REVIEW = 'DISPUTE_UNDER_REVIEW',
  DISPUTE_WON = 'DISPUTE_WON',
  DISPUTE_LOST = 'DISPUTE_LOST',
}

export class OrderEventDto {
  @ApiProperty({ enum: OrderEventType })
  event: OrderEventType;

  @ApiProperty()
  order_id: string;

  @ApiProperty()
  merchant_order_ext_ref: string;
}