version: '3.8'
services:
  pg_db:
    image: postgres:latest
    hostname: pg_db
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    hostname: adminer
    ports:
      - 8088:8080
    networks:
      - backend

  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: nest_app
    restart: always
    depends_on:
      pg_db:
        condition: service_healthy
    ports:
      - ${PORT}:${PORT}
    environment:
      DATABASE_HOST: pg_db
      DATABASE_PORT: 5432
      DATABASE_URL: postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@pg_db:5432/${DATABASE_NAME}?schema=public
    env_file:
      - ../.env
    networks:
      - backend
networks:
  backend:

volumes:
  pg_data:
